#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using McStudDesktop.Models;

namespace McStudDesktop.Services
{
    public class EstimatePresetService
    {
        private static readonly Lazy<EstimatePresetService> _instance = new(() => new EstimatePresetService());
        public static EstimatePresetService Instance => _instance.Value;

        private readonly string _filePath;
        private EstimatePresetsData _data = new();
        private static readonly JsonSerializerOptions _jsonOptions = new()
        {
            WriteIndented = true,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase
        };

        private EstimatePresetService()
        {
            var appDataPath = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                "McStudDesktop"
            );
            Directory.CreateDirectory(appDataPath);
            _filePath = Path.Combine(appDataPath, "estimate_presets.json");
            Load();
        }

        private void Load()
        {
            try
            {
                if (File.Exists(_filePath))
                {
                    var json = File.ReadAllText(_filePath);
                    _data = JsonSerializer.Deserialize<EstimatePresetsData>(json, _jsonOptions) ?? new EstimatePresetsData();
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"[EstimatePresetService] Load error: {ex.Message}");
                _data = new EstimatePresetsData();
            }
        }

        private void Save()
        {
            try
            {
                _data.LastModified = DateTime.Now;
                var json = JsonSerializer.Serialize(_data, _jsonOptions);
                File.WriteAllText(_filePath, json);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"[EstimatePresetService] Save error: {ex.Message}");
            }
        }

        public List<EstimatePreset> GetAllPresets()
        {
            return _data.Presets.OrderByDescending(p => p.TimesUsed).ThenByDescending(p => p.CreatedAt).ToList();
        }

        public EstimatePreset SaveCurrentAsPreset(string name, List<PresetLine> lines)
        {
            var preset = new EstimatePreset
            {
                Name = name,
                Lines = lines,
                IsAutoGenerated = false,
                CreatedAt = DateTime.Now
            };
            _data.Presets.Add(preset);
            Save();
            return preset;
        }

        public void DeletePreset(string id)
        {
            _data.Presets.RemoveAll(p => p.Id == id);
            Save();
        }

        public void RecordUsage(string id)
        {
            var preset = _data.Presets.FirstOrDefault(p => p.Id == id);
            if (preset != null)
            {
                preset.TimesUsed++;
                preset.LastUsedAt = DateTime.Now;
                Save();
            }
        }

        public void GenerateAutoPresets()
        {
            // Remove old auto-generated presets
            _data.Presets.RemoveAll(p => p.IsAutoGenerated);

            try
            {
                var learningService = EstimateLearningService.Instance;
                var allPatterns = learningService.GetAllManualLinePatterns()
                    .Where(p => p.ManualLines.Count >= 2 && p.ExampleCount >= 3)
                    .OrderByDescending(p => p.ExampleCount)
                    .Take(5)
                    .ToList();

                foreach (var pattern in allPatterns)
                {
                    var lines = pattern.ManualLines.Select(m => new PresetLine
                    {
                        PartName = m.ManualLineType.Length > 0 ? m.ManualLineType : m.Description,
                        OperationType = pattern.ParentOperationType ?? "",
                        LaborHours = m.LaborUnits,
                        RefinishHours = m.RefinishUnits,
                        Price = m.AvgPrice
                    }).ToList();

                    var presetName = $"{pattern.ParentPartName} {pattern.ParentOperationType}".Trim();
                    _data.Presets.Add(new EstimatePreset
                    {
                        Name = presetName,
                        Lines = lines,
                        IsAutoGenerated = true,
                        TimesUsed = pattern.ExampleCount,
                        CreatedAt = DateTime.Now
                    });
                }

                Save();
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"[EstimatePresetService] Auto-generate error: {ex.Message}");
            }
        }
    }
}
