#nullable enable
using System;
using System.IO;
using System.Text.Json;

namespace McStudDesktop.Services
{
    public class GhostExportConfig
    {
        public string HeaderTitle { get; set; } = "Damage Guidance Estimate";
        public string HeaderSubtitle { get; set; } = "Generated by McStud Desktop";
        public bool ShowDate { get; set; } = true;
        public string DateFormat { get; set; } = "MMMM dd, yyyy 'at' h:mm tt";
        public string FooterText { get; set; } = "Damage Guidance Estimate";
        public bool ShowPageNumbers { get; set; } = true;

        // Ghost-specific toggles
        public bool ShowVehicleInfo { get; set; } = true;
        public bool ShowSummaryCards { get; set; } = true;
        public bool ShowWarnings { get; set; } = true;
        public bool ShowProTips { get; set; } = true;
        public bool ShowOperationDetails { get; set; } = true;
        public bool ShowSectionSubtotals { get; set; } = true;
        public bool ShowConfidenceLabels { get; set; } = true;
    }

    public class GhostExportConfigService
    {
        private static GhostExportConfigService? _instance;
        public static GhostExportConfigService Instance => _instance ??= new GhostExportConfigService();

        private readonly string _configPath;
        public GhostExportConfig Config { get; private set; } = new();

        public event Action? ConfigChanged;

        private GhostExportConfigService()
        {
            var appDataDir = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
                "McStudDesktop");
            Directory.CreateDirectory(appDataDir);
            _configPath = Path.Combine(appDataDir, "GhostExportConfig.json");
            LoadConfig();
        }

        private void LoadConfig()
        {
            try
            {
                if (File.Exists(_configPath))
                {
                    var json = File.ReadAllText(_configPath);
                    var config = JsonSerializer.Deserialize<GhostExportConfig>(json, new JsonSerializerOptions
                    {
                        PropertyNameCaseInsensitive = true
                    });
                    if (config != null)
                        Config = config;
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"[GhostExportConfigService] Error loading config: {ex.Message}");
            }
        }

        public void SaveConfig()
        {
            try
            {
                var json = JsonSerializer.Serialize(Config, new JsonSerializerOptions
                {
                    WriteIndented = true
                });
                File.WriteAllText(_configPath, json);
                ConfigChanged?.Invoke();
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"[GhostExportConfigService] Error saving config: {ex.Message}");
            }
        }

        public void ResetToDefaults()
        {
            Config = new GhostExportConfig();
            SaveConfig();
        }
    }
}
