#nullable enable
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace McStudDesktop.Services
{
    public class ScrubberPdfExportService
    {
        private static readonly string[] SectionOrder = new[]
        {
            "FRONT BUMPER & GRILLE", "REAR BUMPER",
            "FRONT LAMPS", "REAR LAMPS",
            "RADIATOR SUPPORT",
            "HOOD",
            "FENDER",
            "FRONT DOOR", "REAR DOOR",
            "QUARTER PANEL",
            "PILLARS, ROCKER & FLOOR",
            "ROOF",
            "TRUNK / DECKLID",
            "GLASS",
            "FRAME",
            "RESTRAINT SYSTEMS",
            "ELECTRICAL",
            "INSTRUMENT PANEL",
            "VEHICLE DIAGNOSTICS",
            "MECHANICAL",
            "MISCELLANEOUS OPERATIONS"
        };

        private static readonly Dictionary<string, string> SectionHexColors = new()
        {
            ["FRONT BUMPER & GRILLE"] = "#64B4FF",
            ["REAR BUMPER"] = "#64B4FF",
            ["FRONT LAMPS"] = "#82BEFF",
            ["REAR LAMPS"] = "#82BEFF",
            ["RADIATOR SUPPORT"] = "#64AAF0",
            ["HOOD"] = "#64B4FF",
            ["FENDER"] = "#64B4FF",
            ["FRONT DOOR"] = "#64B4FF",
            ["REAR DOOR"] = "#64B4FF",
            ["QUARTER PANEL"] = "#64B4FF",
            ["ROOF"] = "#64B4FF",
            ["TRUNK / DECKLID"] = "#64B4FF",
            ["GLASS"] = "#82C8F0",
            ["INSTRUMENT PANEL"] = "#82BEFF",
            ["PILLARS, ROCKER & FLOOR"] = "#FF8282",
            ["FRAME"] = "#FF8282",
            ["RESTRAINT SYSTEMS"] = "#FF6464",
            ["VEHICLE DIAGNOSTICS"] = "#64DCB4",
            ["ELECTRICAL"] = "#FFC850",
            ["MECHANICAL"] = "#82C8FF",
            ["MISCELLANEOUS OPERATIONS"] = "#B4B9BE",
        };

        public ScrubberPdfExportService()
        {
            QuestPDF.Settings.License = LicenseType.Community;
        }

        public string GenerateScrubberPdf(
            List<ParsedEstimateLine> parsedLines,
            EstimateScoringResult? scoringResult,
            string? outputPath = null)
        {
            if (string.IsNullOrEmpty(outputPath))
            {
                var documentsPath = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
                var fileName = $"McStud_ScrubberExport_{DateTime.Now:yyyyMMdd_HHmmss}.pdf";
                outputPath = Path.Combine(documentsPath, fileName);
            }

            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.Letter);
                    page.Margin(40);
                    page.DefaultTextStyle(x => x.FontSize(10));

                    page.Header().Element(c => ComposeHeader(c, scoringResult));

                    page.Content().Element(content =>
                    {
                        content.PaddingVertical(10).Column(column =>
                        {
                            column.Spacing(10);

                            // Part 1: YOUR ESTIMATE
                            column.Item().Element(e => ComposeEstimateSection(e, parsedLines));

                            // Part 2: SCRUBBER RESULTS (only if scoring available)
                            if (scoringResult != null && scoringResult.Issues.Count > 0)
                                column.Item().Element(e => ComposeScrubberResults(e, scoringResult));

                            // Recovery summary bar
                            if (scoringResult != null)
                                column.Item().Element(e => ComposeRecoverySummary(e, scoringResult));
                        });
                    });

                    page.Footer().Element(ComposeFooter);
                });
            }).GeneratePdf(outputPath);

            try
            {
                Process.Start(new ProcessStartInfo(outputPath) { UseShellExecute = true });
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"[ScrubberPdfExport] Could not open PDF: {ex.Message}");
            }

            return outputPath;
        }

        private void ComposeHeader(IContainer container, EstimateScoringResult? result)
        {
            container.Column(col =>
            {
                col.Item().Row(row =>
                {
                    row.RelativeItem().Column(titleCol =>
                    {
                        titleCol.Item().Text("Import Scrubber Report")
                            .FontSize(18).Bold().FontColor(Colors.Blue.Darken2);

                        titleCol.Item().Text("Generated by McStud Desktop")
                            .FontSize(11).FontColor(Colors.Blue.Darken1);

                        titleCol.Item().PaddingTop(2).Text($"Generated: {DateTime.Now:MMMM dd, yyyy 'at' h:mm tt}")
                            .FontSize(9).FontColor(Colors.Grey.Darken1);
                    });
                });

                if (result != null && !string.IsNullOrEmpty(result.VehicleInfo))
                {
                    col.Item().PaddingTop(8).Background(Colors.Grey.Lighten3).Padding(10).Column(infoCol =>
                    {
                        infoCol.Item().Row(row =>
                        {
                            row.AutoItem().Text("Vehicle: ").FontSize(10).Bold();
                            row.AutoItem().Text(result.VehicleInfo).FontSize(10);
                        });
                    });
                }
            });
        }

        // ── Part 1: YOUR ESTIMATE ──────────────────────────────────────

        private void ComposeEstimateSection(IContainer container, List<ParsedEstimateLine> lines)
        {
            var grouped = lines
                .GroupBy(l => !string.IsNullOrEmpty(l.Category) ? l.Category.ToUpper() : "MISCELLANEOUS OPERATIONS")
                .OrderBy(g => Array.IndexOf(SectionOrder, g.Key) is int idx && idx >= 0 ? idx : 99)
                .ToList();

            container.Column(col =>
            {
                // Part 1 title bar
                col.Item().Background(Colors.Blue.Darken3).Padding(10)
                    .Text("PART 1: YOUR ESTIMATE")
                    .FontSize(13).Bold().FontColor(Colors.White);

                col.Item().PaddingTop(6);

                foreach (var group in grouped)
                {
                    col.Item().Element(e => ComposeEstimateGroup(e, group.Key, group.ToList()));
                    col.Item().PaddingTop(4);
                }
            });
        }

        private void ComposeEstimateGroup(IContainer container, string sectionName, List<ParsedEstimateLine> lines)
        {
            var accentHex = SectionHexColors.GetValueOrDefault(sectionName, "#969BA0");

            container.Column(col =>
            {
                // Section header
                col.Item().Background(accentHex).Padding(8).Row(row =>
                {
                    row.RelativeItem().Text(sectionName)
                        .Bold().FontSize(11).FontColor(Colors.White);

                    var bodyHrs = lines.Sum(l => l.LaborHours + l.RepairHours);
                    var rfnHrs = lines.Sum(l => l.RefinishHours);
                    var parts = lines.Sum(l => l.Price);
                    var totals = new List<string>();
                    if (bodyHrs > 0) totals.Add($"Body: {bodyHrs:F1}");
                    if (rfnHrs > 0) totals.Add($"Rfn: {rfnHrs:F1}");
                    if (parts > 0) totals.Add($"Parts: ${parts:F2}");

                    row.AutoItem().AlignRight().AlignMiddle().Text(string.Join("  |  ", totals))
                        .FontSize(9).FontColor(Colors.White);
                });

                // Column headers
                col.Item().Background(Colors.Grey.Lighten3).Padding(4).Row(hdr =>
                {
                    hdr.ConstantItem(25).Text("#").FontSize(8).Bold().FontColor(Colors.Grey.Darken2);
                    hdr.ConstantItem(40).Text("Op").FontSize(8).Bold().FontColor(Colors.Grey.Darken2);
                    hdr.RelativeItem(4).Text("Description").FontSize(8).Bold().FontColor(Colors.Grey.Darken2);
                    hdr.ConstantItem(55).AlignRight().Text("Price").FontSize(8).Bold().FontColor(Colors.Grey.Darken2);
                    hdr.ConstantItem(60).AlignRight().Text("Labor").FontSize(8).Bold().FontColor(Colors.Grey.Darken2);
                    hdr.ConstantItem(45).AlignRight().Text("Paint").FontSize(8).Bold().FontColor(Colors.Grey.Darken2);
                });

                // Line rows
                int lineNum = 1;
                foreach (var line in lines)
                {
                    var isEven = lineNum % 2 == 0;
                    var bgColor = isEven ? Colors.Grey.Lighten4 : Colors.White;

                    col.Item().Background(bgColor).Padding(4).Row(opRow =>
                    {
                        opRow.ConstantItem(25).Text(lineNum.ToString()).FontSize(9).FontColor(Colors.Grey.Darken1);

                        var typeCode = line.OperationType switch
                        {
                            "Replace" or "Repl" => "REPL",
                            "Repair" or "Rpr" => "RPR",
                            "Refinish" or "Rfn" => "RFN",
                            "Blend" => "BLD",
                            "Body" => "BODY",
                            "Mech" => "MECH",
                            "Frame" => "FRM",
                            "r&i" or "R&I" => "R&I",
                            _ => line.OperationType?.ToUpper() ?? ""
                        };
                        opRow.ConstantItem(40).Text(typeCode).FontSize(8).FontColor(Colors.Grey.Darken2);

                        opRow.RelativeItem(4).Text(text =>
                        {
                            if (line.IsManualLine)
                            {
                                text.Span("[ADD] ").FontSize(8).Bold().FontColor("#2E7D32");
                            }
                            text.Span(line.Description).FontSize(9);
                        });

                        opRow.ConstantItem(55).AlignRight().Text(line.Price > 0 ? $"${line.Price:F2}" : "")
                            .FontSize(9).FontColor(Colors.Green.Darken2);

                        var bodyHrs = line.LaborHours + line.RepairHours;
                        var laborLabel = bodyHrs > 0 ? $"{bodyHrs:F1}" : "";
                        if (bodyHrs > 0 && !string.IsNullOrEmpty(line.LaborType))
                        {
                            var suffix = line.LaborType switch
                            {
                                "Mechanical" => " M",
                                "Structural" => " S",
                                "Body" => "",
                                _ => ""
                            };
                            laborLabel += suffix;
                        }
                        opRow.ConstantItem(60).AlignRight().Text(laborLabel).FontSize(9);

                        opRow.ConstantItem(45).AlignRight().Text(line.RefinishHours > 0 ? $"{line.RefinishHours:F1}" : "")
                            .FontSize(9).FontColor(Colors.Blue.Darken1);
                    });

                    lineNum++;
                }

                // Subtotals
                var totalBody = lines.Sum(l => l.LaborHours + l.RepairHours);
                var totalPaint = lines.Sum(l => l.RefinishHours);
                var totalParts = lines.Sum(l => l.Price);

                col.Item().Background(Colors.Grey.Lighten2).Padding(4).Row(subRow =>
                {
                    subRow.ConstantItem(25).Text("");
                    subRow.ConstantItem(40).Text("");
                    subRow.RelativeItem(4).Text($"Section Total ({lines.Count} lines)")
                        .FontSize(9).Bold().FontColor(Colors.Grey.Darken2);
                    subRow.ConstantItem(55).AlignRight().Text(totalParts > 0 ? $"${totalParts:F2}" : "")
                        .FontSize(9).Bold().FontColor(Colors.Green.Darken2);
                    subRow.ConstantItem(60).AlignRight().Text(totalBody > 0 ? $"{totalBody:F1}" : "")
                        .FontSize(9).Bold();
                    subRow.ConstantItem(45).AlignRight().Text(totalPaint > 0 ? $"{totalPaint:F1}" : "")
                        .FontSize(9).Bold().FontColor(Colors.Blue.Darken1);
                });
            });
        }

        // ── Part 2: SCRUBBER RESULTS ───────────────────────────────────

        private void ComposeScrubberResults(IContainer container, EstimateScoringResult result)
        {
            // Categorize issues using same logic as CopyToClipboard_Click
            var blendIssues = result.Issues
                .Where(i => i.Category == IssueCategoryType.Blend ||
                            (i.SuggestedFix?.OperationType == "Blend") ||
                            (i.Title?.StartsWith("Blend ") == true))
                .ToList();
            var blendTitles = new HashSet<string>(blendIssues.Select(i => i.Title ?? ""));

            var scoringIssues = result.Issues
                .Where(i => (i.Source == "Scoring" || i.Source == null) && !blendTitles.Contains(i.Title ?? ""))
                .ToList();
            var smartIssues = result.Issues
                .Where(i => i.Source == "Smart" && !blendTitles.Contains(i.Title ?? ""))
                .ToList();
            var learnedIssues = result.Issues
                .Where(i => i.Source == "Learned")
                .ToList();
            var pPageIssues = result.Issues
                .Where(i => i.Source == "PPage")
                .ToList();

            container.Column(col =>
            {
                // Part 2 title bar
                col.Item().Background("#1B3A5C").Padding(10)
                    .Text("PART 2: SCRUBBER RESULTS")
                    .FontSize(13).Bold().FontColor(Colors.White);

                col.Item().PaddingTop(6);

                // 1. Must-Have / Scoring Issues (orange accent)
                if (scoringIssues.Count > 0)
                {
                    col.Item().Element(e => ComposeScoringIssues(e, scoringIssues));
                    col.Item().PaddingTop(6);
                }

                // 2. Commonly Missed (blue accent)
                if (smartIssues.Count > 0)
                {
                    col.Item().Element(e => ComposeSmartIssues(e, smartIssues));
                    col.Item().PaddingTop(6);
                }

                // 3. Blend Considerations (purple accent) — separate from scoring
                if (blendIssues.Count > 0)
                {
                    col.Item().Element(e => ComposeBlendIssues(e, blendIssues));
                    col.Item().PaddingTop(6);
                }

                // 4. Learned Pattern Suggestions (green accent)
                if (learnedIssues.Count > 0)
                {
                    col.Item().Element(e => ComposeLearnedIssues(e, learnedIssues));
                    col.Item().PaddingTop(6);
                }

                // 5. Not-Included Operations (amber accent)
                if (pPageIssues.Count > 0)
                {
                    col.Item().Element(e => ComposePPageIssues(e, pPageIssues));
                }
            });
        }

        // Sub-section 1: Must-Have / Scoring Issues
        private void ComposeScoringIssues(IContainer container, List<ScoringIssue> issues)
        {
            container.Column(col =>
            {
                col.Item().Background("#E65100").Padding(8)
                    .Text($"MUST-HAVE / SCORING ISSUES ({issues.Count} items)")
                    .Bold().FontSize(10).FontColor(Colors.White);

                int num = 1;
                foreach (var issue in issues)
                {
                    var bgColor = num % 2 == 0 ? "#FFF3E0" : "#FFFFFF";
                    col.Item().Background(bgColor).Padding(6).Row(row =>
                    {
                        // Severity badge
                        var badgeColor = issue.Severity switch
                        {
                            IssueSeverity.Critical => "#D32F2F",
                            IssueSeverity.High => "#E65100",
                            IssueSeverity.Medium => "#F9A825",
                            _ => "#757575"
                        };
                        var badgeText = issue.Severity switch
                        {
                            IssueSeverity.Critical => "CRIT",
                            IssueSeverity.High => "HIGH",
                            IssueSeverity.Medium => "MED",
                            _ => "LOW"
                        };
                        row.ConstantItem(35).AlignCenter().AlignMiddle()
                            .Background(badgeColor).Padding(2)
                            .Text(badgeText).FontSize(7).Bold().FontColor(Colors.White);

                        row.ConstantItem(6); // spacer

                        row.RelativeItem().Column(detail =>
                        {
                            detail.Item().Text(issue.Title).FontSize(9).Bold();

                            var meta = new List<string>();
                            if (issue.SuggestedFix?.LaborHours > 0)
                                meta.Add($"Labor: {issue.SuggestedFix.LaborHours:F1}h");
                            if (issue.SuggestedFix?.EstimatedCost > 0)
                                meta.Add($"~${issue.SuggestedFix.EstimatedCost:N2}");
                            if (!string.IsNullOrEmpty(issue.WhyNeeded))
                                meta.Add(issue.WhyNeeded);

                            if (meta.Count > 0)
                                detail.Item().Text(string.Join("  |  ", meta))
                                    .FontSize(8).FontColor(Colors.Grey.Darken2);
                        });
                    });
                    num++;
                }
            });
        }

        // Sub-section 2: Commonly Missed
        private void ComposeSmartIssues(IContainer container, List<ScoringIssue> issues)
        {
            container.Column(col =>
            {
                col.Item().Background("#1565C0").Padding(8)
                    .Text($"COMMONLY MISSED FOR THIS ESTIMATE ({issues.Count} items)")
                    .Bold().FontSize(10).FontColor(Colors.White);

                int num = 1;
                foreach (var issue in issues)
                {
                    var bgColor = num % 2 == 0 ? "#E3F2FD" : "#FFFFFF";
                    col.Item().Background(bgColor).Padding(6).Row(row =>
                    {
                        row.RelativeItem().Column(detail =>
                        {
                            detail.Item().Text(text =>
                            {
                                if (!string.IsNullOrEmpty(issue.TriggeredBy))
                                {
                                    text.Span($"{issue.TriggeredBy} → ").FontSize(8).FontColor(Colors.Blue.Darken2);
                                }
                                text.Span(issue.Title).FontSize(9).Bold();
                            });

                            var meta = new List<string>();
                            if (issue.SuggestedFix?.LaborHours > 0)
                                meta.Add($"Labor: {issue.SuggestedFix.LaborHours:F1}h");
                            if (issue.SuggestedFix?.EstimatedCost > 0)
                                meta.Add($"~${issue.SuggestedFix.EstimatedCost:N2}");
                            if (!string.IsNullOrEmpty(issue.WhyNeeded))
                                meta.Add(issue.WhyNeeded);

                            if (meta.Count > 0)
                                detail.Item().Text(string.Join("  |  ", meta))
                                    .FontSize(8).FontColor(Colors.Grey.Darken2);
                        });
                    });
                    num++;
                }
            });
        }

        // Sub-section 3: Blend Considerations — separate, simpler layout
        private void ComposeBlendIssues(IContainer container, List<ScoringIssue> issues)
        {
            container.Column(col =>
            {
                col.Item().Background("#7B1FA2").Padding(8)
                    .Text($"BLEND CONSIDERATIONS ({issues.Count} items)")
                    .Bold().FontSize(10).FontColor(Colors.White);

                int num = 1;
                foreach (var issue in issues)
                {
                    var bgColor = num % 2 == 0 ? "#F3E5F5" : "#FFFFFF";
                    col.Item().Background(bgColor).Padding(6).Row(row =>
                    {
                        row.RelativeItem().Text(text =>
                        {
                            text.Span(issue.Title).FontSize(9).Bold();
                            if (!string.IsNullOrEmpty(issue.WhyNeeded))
                            {
                                text.Span($"  —  {issue.WhyNeeded}").FontSize(8).FontColor(Colors.Grey.Darken2);
                            }
                        });
                    });
                    num++;
                }
            });
        }

        // Sub-section 4: Learned Pattern Suggestions
        private void ComposeLearnedIssues(IContainer container, List<ScoringIssue> issues)
        {
            container.Column(col =>
            {
                col.Item().Background("#2E7D32").Padding(8)
                    .Text($"LEARNED PATTERN SUGGESTIONS ({issues.Count} items)")
                    .Bold().FontSize(10).FontColor(Colors.White);

                int num = 1;
                foreach (var issue in issues)
                {
                    var bgColor = num % 2 == 0 ? "#E8F5E9" : "#FFFFFF";
                    col.Item().Background(bgColor).Padding(6).Row(row =>
                    {
                        row.RelativeItem().Column(detail =>
                        {
                            detail.Item().Text(issue.Description).FontSize(9);

                            var meta = new List<string>();
                            if (issue.SuggestedFix?.LaborHours > 0)
                                meta.Add($"Labor: {issue.SuggestedFix.LaborHours:F1}h");
                            if (issue.SuggestedFix?.EstimatedCost > 0)
                                meta.Add($"~${issue.SuggestedFix.EstimatedCost:F0}");
                            if (!string.IsNullOrEmpty(issue.WhyNeeded))
                                meta.Add(issue.WhyNeeded);

                            if (meta.Count > 0)
                                detail.Item().Text(string.Join("  |  ", meta))
                                    .FontSize(8).FontColor(Colors.Grey.Darken2);
                        });
                    });
                    num++;
                }
            });
        }

        // Sub-section 5: Not-Included Operations (P-Pages/CEG/DEG)
        private void ComposePPageIssues(IContainer container, List<ScoringIssue> issues)
        {
            container.Column(col =>
            {
                col.Item().Background("#FF8F00").Padding(8)
                    .Text($"NOT-INCLUDED OPERATIONS — P-Pages/CEG/DEG ({issues.Count} items)")
                    .Bold().FontSize(10).FontColor(Colors.White);

                int num = 1;
                foreach (var issue in issues)
                {
                    var bgColor = num % 2 == 0 ? "#FFF8E1" : "#FFFFFF";
                    col.Item().Background(bgColor).Padding(6).Row(row =>
                    {
                        row.RelativeItem().Column(detail =>
                        {
                            detail.Item().Text(text =>
                            {
                                text.Span(issue.Title).FontSize(9).Bold();
                                if (!string.IsNullOrEmpty(issue.Description))
                                {
                                    text.Span($": {issue.Description}").FontSize(9);
                                }
                            });

                            if (!string.IsNullOrEmpty(issue.WhyNeeded))
                                detail.Item().Text($"Source: {issue.WhyNeeded}")
                                    .FontSize(8).FontColor(Colors.Grey.Darken2);
                        });
                    });
                    num++;
                }
            });
        }

        // ── Recovery Summary Bar ───────────────────────────────────────

        private void ComposeRecoverySummary(IContainer container, EstimateScoringResult result)
        {
            container.Background(Colors.Blue.Darken3).Padding(10).Row(row =>
            {
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text("RECOVERY SUMMARY")
                        .FontSize(12).Bold().FontColor(Colors.White);

                    col.Item().PaddingTop(2).Text($"Score: {result.OverallScore}/100  ({result.Grade})")
                        .FontSize(10).FontColor(Colors.Blue.Lighten3);
                });

                row.AutoItem().AlignRight().AlignMiddle().Column(col =>
                {
                    var totalRecovery = result.PotentialCostRecovery;
                    if (totalRecovery > 0)
                    {
                        col.Item().Text($"Potential Recovery: ${totalRecovery:N2}")
                            .FontSize(12).Bold().FontColor(Colors.White);
                    }

                    var parts = new List<string>();
                    if (result.BodyLaborRecovery > 0) parts.Add($"Body: ${result.BodyLaborRecovery:F0}");
                    if (result.PaintLaborRecovery > 0) parts.Add($"Paint: ${result.PaintLaborRecovery:F0}");
                    if (result.MechLaborRecovery > 0) parts.Add($"Mech: ${result.MechLaborRecovery:F0}");
                    if (result.PartsRecovery > 0) parts.Add($"Parts: ${result.PartsRecovery:F0}");

                    if (parts.Count > 0)
                        col.Item().AlignRight().Text(string.Join("  |  ", parts))
                            .FontSize(9).FontColor(Colors.Blue.Lighten3);
                });
            });
        }

        // ── Footer ─────────────────────────────────────────────────────

        private void ComposeFooter(IContainer container)
        {
            container.AlignCenter().Text(text =>
            {
                text.Span("Page ");
                text.CurrentPageNumber();
                text.Span(" of ");
                text.TotalPages();
                text.Span(" | McStud Import Scrubber")
                    .FontSize(8).FontColor(Colors.Grey.Darken1);
            });
        }
    }
}
