#nullable enable
using System;
using System.Collections.Generic;

namespace McStudDesktop.Models
{
    public class EstimatePreset
    {
        public string Id { get; set; } = Guid.NewGuid().ToString("N")[..8];
        public string Name { get; set; } = "";
        public List<PresetLine> Lines { get; set; } = new();
        public bool IsAutoGenerated { get; set; }
        public int TimesUsed { get; set; }
        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime LastUsedAt { get; set; }
    }

    public class PresetLine
    {
        public string PartName { get; set; } = "";
        public string OperationType { get; set; } = "";
        public decimal LaborHours { get; set; }
        public decimal RefinishHours { get; set; }
        public decimal Price { get; set; }
    }

    public class EstimatePresetsData
    {
        public List<EstimatePreset> Presets { get; set; } = new();
        public DateTime LastModified { get; set; } = DateTime.Now;
    }
}
